import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

export async function GET(request: NextRequest) {
  try {
    const authHeader = request.headers.get('authorization');
    const cronSecret = process.env.CRON_SECRET || process.env.INTERNAL_API_KEY;
    
    if (authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const now = new Date();
    const results = { processed: 0, tasksCreated: 0, errors: [] as string[] };

    // Find all users with autopilot enabled
    const userSettings = await (prisma as any).warmLeadsSettings.findMany({
      where: { autopilotEnabled: true },
    });

    for (const settings of userSettings) {
      try {
        const userId = settings.userId;
        let sequenceSteps: any[] = [];
        try { sequenceSteps = JSON.parse(settings.sequenceSteps || '[]'); } catch (error) {
          console.error('Failed to parse sequenceSteps:', error);
        }
        const enabledSteps = sequenceSteps.filter((s: any) => s.enabled);
        if (enabledSteps.length === 0) continue;

        // Find leads that need action today
        const leads = await (prisma as any).warmLead.findMany({
          where: {
            userId,
            status: { in: ['fetched', 'engaged'] },
            nextActionDate: { lte: now },
          },
          include: {
            posts: { where: { isLiked: false, isCommented: false }, take: 1, orderBy: { postDate: 'desc' } },
          },
          take: settings.profilesPerDay || 20,
        });

        for (const lead of leads) {
          const currentStep = lead.currentSequenceStep || 0;
          if (currentStep >= enabledSteps.length) continue;

          const stepConfig = enabledSteps[currentStep];
          if (!stepConfig) continue;

          const action = stepConfig.action;
          let taskData: any = { leadId: lead.id, action };

          // Determine task type and data based on action
          if (action === 'like' && lead.posts?.[0]) {
            taskData.taskType = 'engage_lead_post';
            taskData.postId = lead.posts[0].id;
            taskData.postUrn = lead.posts[0].postUrn;
            taskData.enableLike = true;
            taskData.enableComment = false;
          } else if (action === 'comment' && lead.posts?.[0]) {
            taskData.taskType = 'engage_lead_post';
            taskData.postId = lead.posts[0].id;
            taskData.postUrn = lead.posts[0].postUrn;
            taskData.enableLike = false;
            taskData.enableComment = true;
            taskData.commentText = ''; // Will be generated by AI or use default
          } else if (action === 'follow') {
            taskData.taskType = 'linkedin_follow_profile';
            taskData.profileUrl = lead.linkedinUrl;
            taskData.vanityId = lead.vanityId;
          } else if (action === 'connect') {
            taskData.taskType = 'linkedin_send_connection';
            taskData.profileUrl = lead.linkedinUrl;
            taskData.vanityId = lead.vanityId;
          } else {
            continue;
          }

          // Create pending task
          await (prisma as any).pendingExtensionTask.create({
            data: {
              userId,
              taskType: taskData.taskType,
              taskData: JSON.stringify(taskData),
              priority: 10 - currentStep,
              scheduledFor: now,
              missedSchedule: false,
            },
          });
          results.tasksCreated++;

          // Calculate next action date based on next step
          const nextStepIndex = currentStep + 1;
          let nextActionDate = null;
          let nextAction = null;
          if (nextStepIndex < enabledSteps.length) {
            const nextStep = enabledSteps[nextStepIndex];
            const daysUntilNext = nextStep.day - stepConfig.day;
            nextActionDate = new Date(now.getTime() + daysUntilNext * 24 * 60 * 60 * 1000);
            nextAction = nextStep.action;
          }

          // Update lead
          await (prisma as any).warmLead.update({
            where: { id: lead.id },
            data: {
              currentSequenceStep: nextStepIndex,
              nextActionDate,
              nextAction,
            },
          });
        }

        results.processed++;
      } catch (e: any) {
        results.errors.push(`User ${settings.userId}: ${e.message}`);
      }
    }

    // Also check for missed tasks and mark them
    const missedTasks = await (prisma as any).pendingExtensionTask.updateMany({
      where: {
        status: 'pending',
        scheduledFor: { lt: new Date(now.getTime() - 60 * 60 * 1000) }, // More than 1 hour late
        missedSchedule: false,
      },
      data: { missedSchedule: true },
    });

    return NextResponse.json({
      success: true,
      ...results,
      missedTasksMarked: missedTasks.count,
      timestamp: now.toISOString(),
    });
  } catch (error: any) {
    console.error('Warm leads cron error:', error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  return GET(request);
}
